### ISSUE TITLE
roscore is failing to start on the-mac-mini

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/continuous_integration#100]
Apparently something is broken with the ros setup on the-mac-mini. It fails to start. One is still running (on the default port). But starting a new one is failing:
```
aslw039050:~ macmini-admin$ export ROS_MASTER_URI=http://aslw039050.ethz.ch:12000/
aslw039050:~ macmini-admin$ roscore -p 12000
... logging to /Users/macmini-admin/.ros/log/6db237a1-bafb-11e6-abb0-0c4de9ce5a87/roslaunch-aslw039050.ethz.ch-79942.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt

started roslaunch server http://aslw039050.ethz.ch:50928/
ros_comm version 1.11.20


SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES

auto-starting new master
process[master]: started with pid [79949]
ROS_MASTER_URI=http://aslw039050.ethz.ch:12000/

setting /run_id to 6db237a1-bafb-11e6-abb0-0c4de9ce5a87
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/launch.py", line 654, in launch
    self._setup()
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/launch.py", line 631, in _setup
    self._launch_core_nodes()
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/launch.py", line 506, in _launch_core_nodes
    name, success = self.launch_node(node, core=True)
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/launch.py", line 534, in launch_node
    process = create_node_process(self.run_id, node, master.uri)
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/nodeprocess.py", line 139, in create_node_process
    args = create_local_process_args(node, machine)
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslaunch/node_args.py", line 251, in create_local_process_args
    matches = roslib.packages.find_node(node.package, node.type, rospack=rospack)
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslib/packages.py", line 400, in find_node
    return find_resource(pkg, node_type, filter_fn=_executable_filter, rospack=rospack)
  File "/opt/ros/indigo/lib/python2.7/site-packages/roslib/packages.py", line 497, in find_resource
    source_path_to_packages = rospack.get_custom_cache('source_path_to_packages', {})
AttributeError: 'RosPack' object has no attribute 'get_custom_cache'
[master] killing on exit
```

Any ideas? Somebody willing to spend time here?

**Comment by helenol** [comment]
I'll take a look, I updated some packages recently... Probably my fault.

**Comment by helenol** [comment]
Wow, that was easy. :) Fixed as per https://github.com/jsk-ros-pkg/jsk_travis/issues/170 by `pip install rospkg --upgrade`. Let me know if there's any more issues!

**Comment by HannesSommer** [comment]
Awesome! Thanks a lot! 
I just had my Mac budget full for today ;) and wasn't bold enough to upgrade something without having any indication that there might be the problem!
